# docker-compose.prod.yml (production config)

services:
  nginx:
    ports:
      - "80:80"
      - "443:443"  # SSL ports
    restart: always
    environment:
      - ADMIN_EMAIL=${ADMIN_EMAIL}
    networks:
      - transcendence

  backend:
    ports:
      - "127.0.0.1:3100:3100"
    restart: always
    networks:
      - transcendence

  frontend:
    build: ./frontend
    container_name: frontend
    volumes:
      - public:/app/public
    networks:
      - transcendence

