{
 "title": "App health status",
 "description": "This dashboard presents the metrics of the main containers to monitor the health of the app.",
 "panels": [
  {
   "title": "Backend: heap memory available",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "nodejs_heap_space_size_available_bytes",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backend server: lag event loop",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "nodejs_eventloop_lag_seconds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Backend heap memory used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "nodejs_heap_size_used_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Number of active Pong games",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 16 },
   "targets": [
    { "expr": "pong_games_active", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Services UP",
   "type": "stat",
   "gridPos": { "h": 9, "w": 9, "x": 10, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "up", "legendFormat": "{{label_name}}" }
   ]
  }
 ]
}