name: Docker Compose Build Check

on:
  push:
    branches: [ main, develop1, marc-develop1 ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to Docker Hub (if needed)
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
      
    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/v2.23.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        
    - name: Build containers
      run: |
        make
        docker-compose -f ./containers/docker-compose.yml down
        
    - name: Verify containers are running
      run: |
        docker ps --format "{{.Names}}" | grep -q fastify
        docker ps --format "{{.Names}}" | grep -q nginx
        docker ps --format "{{.Names}}" | grep -q adminer
